# 34 NumPy Exercises with Hints (APPF1 Version)

This is a collection of exercises that have been selected from <https://github.com/rougier/numpy-100> for this specific course.

A few hints on how to proceed with the exercises: 
* Use IPython's `?` operator to read documentation on the functions, e.g. `np.any?`
* Try to come up with a naive solution first, and only think about a better solution after, i.e. if you can use any NumPy functions or structs to simplify your code. For example, it's not wrong to try to iterate through an array and change every element in a first version (and yes, there probably is an easier way to do it with NumPy functions)
* Feel free to always ask questions if you're stuck
* Using pen and paper to come up with a solution idea is helpful in a lot of situations
* [google.com](http://www.google.com) and [stackoverflow.com](http://www.stackoverflow.com) are your best buddies while programming; trust me, I'm speaking from experience!


#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [19]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [20]:
print(np.__version__)
np.show_config()

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [21]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [22]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [23]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [24]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: Use slicing)

In [25]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 array with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [26]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [27]:
x = [[1,2,0],[0,4,0]]
print(np.nonzero(x))
nz = np.nonzero([1,2,0,0,4,0])
print(nz.__len__())
print(nz)

(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64))
1
(array([0, 1, 4], dtype=int64),)


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [28]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.8105945  0.41737957 0.28991781]
  [0.22076537 0.63465071 0.93998849]
  [0.38298789 0.6269748  0.94625321]]

 [[0.53116969 0.03174023 0.35104567]
  [0.30049736 0.61455364 0.65458761]
  [0.1052421  0.5676958  0.46739831]]

 [[0.27202983 0.61883237 0.46242258]
  [0.58626477 0.49951046 0.37189291]
  [0.40754104 0.67834838 0.72626999]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [29]:
Z = np.random.random((10,10))
np.max(Z, axis=0)
Zmin, Zmax = Z.min(axis=0), Z.max()
print(Zmin, Zmax)

[0.15063013 0.04172172 0.00190291 0.28937555 0.09515358 0.00247737
 0.06461023 0.04910743 0.06448628 0.02506643] 0.9877425176353442


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [30]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.42595857316954705


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: Use slicing)

In [31]:
Z = np.ones((10,10), dtype=int)
Z[1:-1,1:-1] = 0
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 18. Create a 5x5 array with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [32]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 array and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [65]:
Z = np.zeros((8,8),dtype=int)
print(type(Z))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


<class 'numpy.ndarray'>
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. With the help of Boolean masking, extract from the array `np.array([3,4,6,10,24,89,45,43,46,99,100])` the numbers (★☆☆) 

* which are not divisible by 3
* which are divisible by 5
* which are divisible by 3 and 5
* which are divisible by 3 and set them to 42

(**hint**: Use the modulo operator and logical_and)


In [34]:
import numpy as np
a = np.array([3,4,6,10,24,89,45,43,46,99,100])
print(a[a%3!=0])
print(a[a%5==0])
print(a[np.logical_and(a%3==0, a%5==0)])
a[a%3==0]=42
a

[  4  10  89  43  46 100]
[ 10  45 100]
[45]


array([ 42,   4,  42,  10,  42,  89,  42,  43,  46,  42, 100])

#### 22. Normalize a 5x5 random array (★☆☆) 
(**hint**: (x - mean) / std)

In [35]:
Z = np.random.random((5,5))
print(Z.dtype)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)
print(Z.mean())

float64
[[-0.07986448 -1.50131232 -1.08482953  1.33201649  1.68988318]
 [ 1.49626768 -0.4779854  -1.44945779 -0.54247072  1.35023893]
 [-0.67014641 -1.06018287 -0.72294548 -0.5740843  -0.4988583 ]
 [-1.08069444  1.42186873  0.40047665 -0.09497946  0.49643451]
 [ 1.41868189  0.85445735 -1.05313409  0.10800494  0.32261524]]
6.217248937900877e-17


#### 24. Multiply a 5x3 array by a 3x2 array (real array product) (★☆☆) 
(**hint**: np.dot | @)

In [36]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=, optional `out` argument)

In [37]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [38]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 6 8]


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [39]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 37. Create a 5x5 array with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [40]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [56]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.27716481 0.30717221 0.47937767 0.58485977 0.74354508 0.76411105
 0.77392783 0.92184679 0.92478985 0.95288344]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [43]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [44]:
X = np.array([1,2,2])
print(np.max(X))
X[X == np.max(X)] = 0
print(X)

[0.         0.10202009 0.15664403 0.9905911  0.54054652 0.71380284
 0.90942722 0.48063183 0.23060047 0.07663573]


#### 50. How to find the closest value (to a given scalar) in a vector to another given value? (★★☆)

(**hint**: argmin)

In [57]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
16.047934434142917
16


#### 58. Subtract the mean of each row of a array (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [58]:
X = np.random.rand(5, 10)

# Recent versions of numpy
print(X)
print(X.mean(axis=1, keepdims=True))
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[0.06366407 0.58611768 0.66879336 0.48205471 0.94520224 0.28331559
  0.73702149 0.46095132 0.5727422  0.63908883]
 [0.71403296 0.8720151  0.74183505 0.34791661 0.49789284 0.93584137
  0.42006596 0.71616547 0.10704857 0.67307213]
 [0.55539915 0.65828276 0.08875522 0.67600218 0.05953564 0.41013415
  0.81040632 0.34476608 0.16309589 0.76456441]
 [0.20997289 0.79751916 0.36907756 0.18129046 0.03024897 0.2943527
  0.34380294 0.78167603 0.30535174 0.25436256]
 [0.36157981 0.17318985 0.32402816 0.98099142 0.41782123 0.98256514
  0.6386141  0.36677001 0.95813108 0.27277446]]
[[0.54389515]
 [0.60258861]
 [0.45309418]
 [0.3567655 ]
 [0.54764653]]
[[-0.48023108  0.04222253  0.12489822 -0.06184044  0.40130709 -0.26057956
   0.19312634 -0.08294383  0.02884705  0.09519368]
 [ 0.11144435  0.26942649  0.13924645 -0.254672   -0.10469577  0.33325276
  -0.18252264  0.11357686 -0.49554004  0.07048353]
 [ 0.10230497  0.20518858 -0.36433896  0.222908   -0.39355854 -0.04296003
   0.35731214 -0.1083281  -0.2

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [60]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 9 1]
 [1 2 5]
 [1 0 2]]
[[1 0 2]
 [1 2 5]
 [1 9 1]]


#### 60. How to tell if a given 2D array has zero columns? (★★☆)
(**hint**: any, ~)

In [61]:
Z = np.random.randint(0,3,(3,10))
print(Z)
Y = Z.any(axis=0)
print(Y)
print(~Y.any())

[[2 1 0 1 0 0 0 1 0 1]
 [0 2 0 1 1 1 0 0 0 2]
 [1 2 0 1 1 2 0 0 2 1]]
[ True  True False  True  True  True False  True  True  True]
False


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [49]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.79053309, 1.42267459, 0.76027835, 1.76915106, 1.55133009])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [50]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [51]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [52]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.88022505,  0.74541359,  0.9063879 , -0.16946456, -0.4699642 ,
       -0.39097576,  0.64035754, -0.09900399,  0.72327278,  0.36585436,
        0.27724248,  0.71213877, -0.30304305,  0.5673462 ,  0.83688021,
       -0.94083043,  0.71862058,  0.82416129,  0.8122427 ,  0.60776647,
       -0.53892695, -0.58554817, -0.31011506,  0.59996008,  0.05830859,
       -0.82453892,  0.26008177,  0.27049439, -0.71106825,  0.32948827,
        0.5288871 ,  0.03864018,  0.3375653 ,  0.8227437 , -0.27309513,
        0.5733926 ,  0.76898938, -0.97534529,  0.54823563,  0.36437004,
        0.60016965,  0.68834868,  0.67608314,  0.65771335,  0.51815053,
       -0.61591339, -0.13901411,  0.3060007 , -0.81018804, -0.91347196,
       -0.5641858 , -0.90794953,  0.78944997,  0.90974026, -0.12845148,
        0.34437852,  0.86852534, -0.66656293,  0.88557265,  0.03860659,
       -0.23357504, -0.3469611 ,  0.62312914,  0.1651803 ,  0.78177181,
       -0.15065524,  0.15445839, -0.52437778, -0.173886  , -0.01